<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Text Visualization</title>
	<link rel="stylesheet" href="multi-list.css" >
	

<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $('input[type="checkbox"]').click(function(){
        var inputValue = $(this).attr("value");
        $("." + inputValue).toggle();
    });
});
</script><!--------------------------->
    
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myList li").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>    
</head>

<body>
		<h1>List</h1>
        
        
		<div class="list_container ml-input-container">
            <input id="myInput" class="ml-input-filter" type="text" placeholder="Filter" name="Search" >
            <ul id="myList" class="ml-ul">
			<?php
			error_reporting(E_ERROR | E_PARSE);
			$dir = "./AtlanticStormText/Documents";
			$myArray = array();

			if (is_dir($dir)) 
			{
				if ($dh = opendir($dir)) 
				{
					
					$abc = array();
					$two = array();
					for($i=0; $i<=116 ; $i++)
					{
						$file = readdir($dh);
						$record = file_get_contents("C:/Users/milan/Desktop/project/AtlanticStormText/Documents/".$file);
						$abc[] = $file;
						$two[] = $record;
					}	
					$myArray = array_combine($abc, $two);    
				}		
				$d = " ' ";
				$sliced = array_slice($myArray, 2, count($myArray)-2, true);
				foreach($sliced as $key => $value)
				{
					
				echo '<li class="ml-li list_list_item"><label><input type="checkbox" name="colorCheckbox" value='.$key.' >' .$key. '</label></li>';
            
				}
			}
			?>
            </ul>
		</div>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
         <script>
  $( function() {
    $( "#sortable" ).sortable();
    $( "#sortable" ).disableSelection();
  } );
  </script><!--------script for drag and drop text---------->
        
        <div id="sortable" class="list_container work">
        	<h2>Workspace</h2>
            <div class="CIA_01 box">A Russian named Igor Kolokov was arrested in Cairo on 29 January, 2003 and charged with assault on an Egyptian police officer who had attempted to arrest him for being drunk in public. Kolokov sells medical supplies throughout the Middle East and represents a company in Moscow called Medikat. A background check on Kolokov reveals that he was formerly an administrator at the Soviet institute Vector in Strizi, near Kirov in Russia. When he was arrested, Kolokov was carrying a card with a note on it reading [in Russian]: "Safrygin for H. Q., Peshawar."..</div>
    <div class="CIA_02 box">(a) David Loiseau, Canadian citizen from Toronto. Kanjak Training Camp, 2000-2001; wounded near Gizab, March 2002. (b) Raeed Beandali, American, Detroit MI., Mine warfare training, Al Khaldun training camp, 2000-2001; wounded near Qalat, 26 November, 2002; sent to London 12 December, 2002. (c) Fahd Khadr, Canadian, Montreal. Light weapons training Al-Badr I training camp, 1999-2000. Sent home 23 October, 2000..</div>
    <div class="CIA_03 box">Surveillance report on Cesar Arze, whose residence is 77 Avenue Francis, Santo Domingo, Dominican Republic. Arze, who moved from Havana, Cuba to Santo Domingo in 1992, works as a medical technician in Santo Domingo. Arze is under surveillance because of information that he is associated with Cuban intelligence services. Arze was photographed in company with a man identified as Hector Lopez in Bogota, Columbia on 23 January, 2003. Lopez, a known representative of FARC, has conducted narcotics distribution activities throughout South and Central America and the Caribbean..</div>
    <div class="CIA_04 box">This source reports observing, near Calamar on 3 March, 2003, three men he knew were Cubans discussing the transfer of cocaine with members of the National Liberation Army [ELN] in Columbia. The source recognized one of these Cubans as Jose Escalante. This source says that he knew Escalante when they were students in 1991 at a school for medical laboratory technicians in Havana. This source said he believes that Escalante works in some capacity for the Cuban military. Our source also stated that Cuban representatives frequently visit in the tri-border area of Columbia, Ecuador and Peru to arrange for the exchange of weapons of various sorts needed by ELN for cocaine, that the ELN supplies to the Cubans who sell and distribute this narcotic throughout the Caribbean and Central American region..</div>
    <div class="CIA_05 box">Pyotr Safrygin was formerly director of security at the Vector institute in Strizi, Russia. He now holds the position of director of security for Central Russia Airlines. He was born in Lipetsk, Russia on 26 December, 1950 and now lives in Moscow..</div>
    <div class="CIA_06 box">(a) Saeed Hasham [aliases: Hamid Qatada, Yasir Salman]. Member of central staff, Al Qaeda; headed Farooq training camp in Khost area; name appears on many planning documents for insurgent activities in 2002 at Jorm, Taloqan, and the Salang tunnel; received special notice from Osama bin Laden on 22 September 2002 for his planning of successful insurgent actions. (b) Khalid Taha [no recorded aliases], an Egyptian who headed the Spin Shaga camp in Pakhtia province for Kashmiri militants; specializes in chemical weapons. (c) Fahd al Badawi [no recorded aliases]; a Saudi with a medical degree from University of Cairo, Egypt having a specialty in immunology; on medical staff at Farooq training camp in 2001; awarded for successfully treating Osama bin Laden for a bacterial infection in July, 2000..</div>
    <div class="CIA_07 box">On 2 April, 2003 the Surete' de l'Etat issued a bulletin concerning a Moroccan named Abdillah Zinedine [alias: Abu Hafs] who had, among others, been occupying a house at 73 Rue Duhesme. Zinedine had been wanted in connection with an attempt to blow up (faire sauter) the Amercan Embassy in Paris in the Fall of 2001. Zinedine is an explosives expert who was in Afghanistan from 1997 - 2000 and who provided Al Qaeda members with explosives training at the Al Badr II training camp in the Pakhtia province area of Afghanistan. It has recently been learned that Zinedine left Paris on a flight to Montreal, Canada on 1 April, 2003. He was using a fraudulent French passport in the name Mehdi Rafiki. Another occupant of the house at 73 Rue Duhesme, on interrogation, reported that Abu Hafs, as he knew Zinedine, said he was on his way to Chicago to visit an old friend whom he only identified as Murad. This source, identified as another Moroccan Zakarya Ziyad, said that Zinedine had mentioned that he and Murad would be doing "great things" in several cities in America..</div>
    <div class="CIA_08 box">Mohamed al Omari is a Saudi who was apprehended by Pakistani police in Peshawar on 12 January 2003. Omari was badly wounded at the time, saying that he was shot while attempting to desert from an Al Qaeda insurgent group that had taken refuge near Parachinar on the Afghanistan-Pakistan border. Omari was placed in a hospital and, after his recovery, he was encouraged to talk about his Al Qaeda activities. Among the items of information Omari revealed was that he had been at the Farooq training facility in 2001 before the American presence in Afghanistan. He was shown photos of various persons and asked if he could identify any of them. One photo, that had been taken in Peshawar on 2 January, 2003, showed a group of four men. Omari said he knew three of them since they had been with him at the Farooq training camp. One man he identified as Dr. Badawi, the second he identified as Mamdouh al Hazmi, and the third he identified only as Hasham; Omari could not remember his first name. Omari said that all three were members of Al Qaeda..</div>
    <div class="CIA_09 box">This source reported that over 500 carats of polished diamonds were traded by an organization representing rebel forces in Liberia for an assortment of weapons. The person acquiring the diamonds from this organization was identified only as an Arab businessman who had done such trading in the past. This person requested that these diamonds be sent to an address in Panama City, Panama, which he gave as: 993 Panamico Ave. The package, to be delivered to a Ramundo Ortiz at this address, was to be marked for customs purposes as art objects having a commercial value of $250.00..</div>
    <div class="CIA_10 box">In response to our query about other associates of Omar Mahmoud Othman at the Baker St. Mosque in London, MI 5 responded with information that a man named Omar Hanif had been given employment by Othman at this mosque in the period 1993 - 1998. He left the UK for a year in 1999 and was possibly in Afghanistan. Travel records show that he traveled from London Heathrow to Islamabad in February of 1999 and returned to London from there in December, 1999. Hanif holds a valid British passport and now lives at #11 Apple St. in Nassau, The Bahamas. He is employed by a chain of hotels in the Bahamas and works at the Seashore Hotel in Nassau and, occasionally, at the Freeport Star Hotel in Freeport. Another name mentioned by MI 5 to be associated with Othman was Jamal al Quso, who came to the UK from Yemen in 1993. He applied for British citizenship in 1998 but was refused because of his repeated troubles with the law. He was convicted of inciting to riot in 1996 and served a one-year suspended sentence. Records reveal that he left London Heathrow on a flight to Chicago, Illinois on July 17, 1999..</div>
    <div class="CIA_11 box">A house at #88 Sahibzada Gul Rd. in Peshawar, suspected of being an Al Qaeda safe house, was raided on 15 May, 2003 by Pakistani Intelligence. Unfortunately, apparently being tipped-off, the occupants had fled the day before. However, in the mess they left behind, there were a few items of interest. One was an expired Pakistani passport issued to a person named Yasir Salman. Other items included a doctor's stethoscope; notes taken in Arabic on Legionella and gastroenteritis; and notes, written in Arabic, about the results of a May, 2002 project in the USA called TOPOFF I. In addition, an opened envelope addressed in Arabic to F. Badawi was found behind a cabinet in one of the rooms in this house. Finally, a note written in Arabic simply stated: "Karachi, March 10, 2003, Safrygin, funds."..</div>
    <div class="CIA_12 box">A number of bombings were attempted in Casablanca on 16 May, 2003. Of five attempts only one succeeded in causing mass casualties. In four of the attempts that failed only the bombers were killed. These bombings are believed to have been the actions of local individuals who may have been trained by Al Qaeda in Afghanistan. A person believed to have been a participant in the successful bombing was apprehended on 18 June, 2003; his name is Mohamed Essabar. On interrogation, Essabar was asked to reveal the names of other participants, which, even under duress, he refused to do. However, when he was arrested he was carrying a note in Arabic signed by a person named A. Atmani. One person of interest having this name is Abdellah Atmani, who has been a resident of Casablanca all his life. During interviews with Atmani, it became clear that he had no part in the bombings on 16 May, 2003. However, his name was brought to our attention because Atmani works as a loading supervisor for the Holland Orange Shipping Lines that has offices and docks in Casablanca. Holland Orange ships make regular freight runs from Casablanca to a variety of locations along the east coast of the USA as well as to places in the Caribbean. Moroccan police reported that they were keeping Atmani under surveillance..</div>
    <div class="CIA_13 box">On 20 June, 2003, three men were arrested at # 71 Voorburg straat in Amsterdam. All three men were of Indonesian origin and had emigrated to The Netherlands in the mid 1990s. These men were arrested on evidence that they had formed a plan to destroy a number of Jewish synagogues in Amsterdam and in other places in The Netherlands. One person was identified as being of special interest to us; his name was established as Riduan Sungkar, who was born in Kuala Lumpur in 1974. When he was taken by the police, Sungkar was carrying an airline ticket from Schiphol Airport in Amsterdam to Chicago, IL with a connecting flight to Los Angeles, CA. The departure date on this ticket was 23 June, 2003. He was also carrying a Dutch passport in the name: Omar Evertts, giving his address as # 71 Voorburg straat, Amsterdam. In addition, he had a small notebook containing several names and addresses, two of which were of persons located in the Los Angeles area. They are: A. Somad, 235 Buckthorn St, Inglewood CA, and Y. Bafaba, 773 Flaxton St., Culver City, CA..</div>
    <div class="CIA_14 box">Biographical information was requested on Ramundo Ortiz in Panama City. Records reveal that Ortiz runs a business that deals with art objects as well as precious stones. He is known to be an expert evaluator of diamonds and tanzanites. His business is located at 993 Panamico Ave in Panama City. He travels extensively throughout Central and South America. He is also known to have traveled to Havana, Cuba on many occasions. He is known not to be associated with narcotics traffic in any way. He appears quite prosperous and supports many local charities. But it is also known that he does business with a variety of clients in Africa and the Middle East, especially in Iran and Pakistan..</div>
    <div class="CIA_15 box">A Pakistani citizen volunteered on 15 July, 2003, for a price, to provide information about what happened to the former occupants of #88 Sahibzada Gul Rd. in Peshawar. All he could say is that he knew they went north, most likely to Chitral. Asked to provide more information about the previous occupants, all he would say is that he knew they were Al Qaeda. A footnote to this story is that, on 17 July, this informer was found with his throat slit in a back alley in Peshawar..</div>
    <div class="CIA_16 box">Based on the NSA report of 1 July, 2003, information was solicited from RCMP regarding the activities of an R. Derwish who lives at 811 Tecumseh Rd. in Windsor, Ontario. The RCMP report that this person's name is in fact Satam Derwish, a Saudi who has used the first name Ronald since he arrived in Canada in 1992. Derwish now holds a Canadian passport. Derwish has been under surveillance recently by the RCMP because of his associations with suspected Hezbollah members in Windsor and in Detroit, Michigan. Derwish works as a ticket agent for Canada Eastern Airlines in Windsor. He gets frequent trips at low cost to various places in the USA and has traveled recently to Newark, NJ, Chicago, IL, and Columbus, Ohio, all of which are cities served by Canadian Eastern Airlines..</div>
    <div class="CIA_17 box">Based on a NSA intercept reported on 12 September, 2003, information was requested about a person named Bugarov, presumably Russian, who might have had contact with Pyotr Safrygin at the Vector Institute in Moscow. It is believed that a Boris Bugarov worked as a scientist on bioweapons at Vector between the years 1986 and 1990. In 1990 he traveled to Havana, Cuba with a Maj. Gen. Yury Kalinin, but returned to Moscow shortly thereafter. He has not been seen since then; but sources in Russia say he has returned to Cuba and now lives in Havana where he works in some capacity for the Cuban government..</div>
    <div class="CIA_18 box">Further information was requested on Muslih Odeh, who was mentioned in an NSA report of 15 September, 2003. MI 6 reported that Muslih Odeh is believed to be a Saudi and is not a British citizen. Saudi Intelligence reported that a Muslih Odeh was born in Jeddah in 1967 and was last recorded as living in Saudi Arabia in Riyadh in 1998..</div>
    <div class="CIA_19 box">One of the men identified in the photo taken in Peshawar on 2 January, 2003, mentioned in the CIA report of 20 April, 2003, was a Mamdouh al Hazmi. This person is a Saudi known to have been associated with Al Qaeda. Recently obtained records reveal that a Mamdouh al Hazmi was killed in a firefight with American forces on 12 March, 2003 near Orgun in Afghanistan..</div>
    <div class="CIA_20 box">A paid source in Chitral said he was treated on about 2 October, 2003 for a broken arm by a Dr. Badawi in a refugee camp outside Chitral. Asked how he knew it was a Dr. Badawi, the source replied that another refugee had told him who this doctor was..</div>
    <div class="CIA_21 box">Query regarding Cubans registering at Casablanca hotels. Carlos Araneda, Havana, Cuba, registered at the Moroccan Sands Hotel on 19 October, 2003; checked out on 22 October, 2003. Jose Escalante and B. Bugarov, both of Havana, Cuba, registered together at Sahara Atlantic Hotel on 21 October, 2003; checked out on 23 October, 2003. Arnoldo Ramirez, San Cristobal, Cuba, registered at Sahara Atlantic Hotel on 18 October, 2003; checked out on 22 October, 2003..</div>
    <div class="CIA_22 box">Query regarding persons from Pakistan registering at Casablanca hotels between 19 - 24 October, 2003. At Moroccan Oasis Hotel: Ali Talib [Karachi], 20 - 24 October; Abu Adil [Karachi], 21 - 22 October; Omar al Banna [Peshawar], 21 - 25 October; Nadia Mahfouz [Peshawar], 22 - 24 October; Ali Mishal [Islamabad], 19 - 24 October. At Sahara Atlantic Hotel: Abdel Noufal [Peshawar], 22 - 23 October; Ahmad Miner [Karachi], 19 -21 October; Yasir Salman [Karachi], 20 - 23 October; Jamat Syeed [Hyderabad], 20 - 23 October. At Moroccan Sands Hotel: Shukri Azzam [Hyderabad]; Nidal Awad [Peshawar],22 - 23 October..</div>
    <div class="CIA_23 box">Response to a query regarding the person at 65 Avenue San Martin in Santo Domingo [see NSA report 1 November, 2003]. Resident at this address is listed as Carlos Morales. Morales works as a taxi driver for the AutoFleet taxi company in Santo Domingo. Records reveal that Morales applied for Dominican Republic citizenship in 2000, which was granted in February of 2001. His birth certificate shows that he was born in Buenos Aires, Argentina on 4 March, 1970. A source who took several rides in a taxi driven by Morales says that he overheard Morales speaking in fluent Arabic to someone he had called using the phone in his cab..</div>
    <div class="CIA_24 box">Surveillance of Omar Hanif reveals that he traveled from Nassau, The Bahamas to Cairo, Egypt on 20 December, 2003 and returned on 25 December, 2003. While in Cairo he was photographed coming out of a shop at 411 Ramses St. in Cairo. He was in the company of two other men. Provided with this photo, we were able to identify one of the two men as Saeed Hasham..</div>
    <div class="CIA_25 box">A check on the activities of Ramundo Ortiz reveals that on 27 January, 2004 he sent a wire transfer of $150,000 in Cuban pesos from the Canal Bank in Panama City to the Peoples Bank in Havana, Cuba. This transfer was to an account held by Jose Escalante at the Peoples Bank..</div>
    <div class="CIA_26 box">Surveillance continues on Omar Hanif in Nassau, The Bahamas. On 4 February, 2004 Hanif took a flight from Nassau to Miami, FL. where he boarded a flight to London, arriving on 5 February. He then took a connecting flight to Karachi, Pakistan, returning by the same route on 7 February. While in Karachi, Hanif stayed at a residence at 631 Nishtar Rd. This house is now under surveillance by Pakistani Intelligence..</div>
    <div class="CIA_27 box">On 17 February, MI 6 requested information on a Malaysian named Ali Sufaat, who is reported to be working for the Caribbean Cargo Shipping Lines in Caracas, Venezuela. Our sources could only say that Sufaat has worked for Caribbean Cargo intermittently and is reported to have left Caracas for either Cuba or the Bahamas. It is known that Sufaat has traveled to both of these places during his work at Caribbean Cargo..</div>
    <div class="CIA_28 box">Response to a request for information about Holland Orange Shipping Lines routes from Casablanca to destinations in the USA and surrounding areas. This shipping line has two freighters, Dutch Courage and Orange Queen, that regularly deliver cargo to Miami, FL., Savannah, GA., and Norfolk, VA., in the USA. These ships also make deliveries to Santo Domingo, Dominican Republic, and to Caracas, Venezuela. The Orange Queen services ports in the USA and the Dutch Courage services ports in the Dominican Republic and Venezuela..</div>
    <div class="CIA_29 box">The Itar-Tass news Agency reported that, on 15 April, 2004, cattle in the city of Blagoveshchensk were found to have foot and mouth disease. One thousand cattle have already been slaughtered. A state of emergency has been declared in six districts of the Amur region..</div>
    <div class="CIA_30 box">Sources tracking Cesar Arze in Santo Domingo report that, on 1 May, 2004, Arze was photographed at a park in Santo Domingo in company with Carlos Morales and a man now identified as a Cuban named Jose Escalante. It is now known that Arze and Escalante received training together in 1992 - 1993 at a school for medical technicians in Havana, Cuba. Arze has been suspected of associations with Cuban intelligence [See CIA Report 22 February, 2003]. Additional information is now available on Carlos Morales, who was overheard speaking fluent Arabic [see CIA Report 15 November, 2003]. Our sources in Buenos Aires, Argentina report that there is a considerable traffic in forged birth certificates among members of the Islamic community in Argentina..</div>
    <div class="CIA_31 box">Further information about the background of Boris Bugarov is provided. From information gathered some time ago from Russian sources, Bugarov was born in 1950 in the town of Saratov and was trained in biology at Moscow State University. He appears to have joined the Vector institute around 1986 and he became an expert in developing aerosolized forms of biological weapons. It is believed Bugarov worked on aerosolized forms of India-1 smallpox and pneumonic plague. More recent sources say that Bugarov went to Cuba but then returned to Moscow sometime in 1992. He is reported to have divorced his wife in 1993 and has returned to Cuba. However, he still travels frequently to Europe, the Middle East and in South America. It is also known that Cuba has an active biological weapons program..</div>
    <div class="CIA_32 box">Further information provided by MI 5 regarding Muslih Odeh [see CIA Report: 25 September, 2003]. MI 5 reports that there is no record of Odeh's having a British passport, but he may have a Saudi passport. He is known to be employed by the Freeport Star Hotel in Freeport, The Bahamas and is currently under surveillance..</div>
    <div class="CIA_33 box">This report was issued in response to an FBI request for information regarding Abdul Nasser and Ali al-Omari. It is known that an Abdul Ahmed Nasser ran a chemical weapons training program in Afghanistan at the Al Khuldan camp in the Khost area from 1999 - 2001 [also see DIA Report for 12 February, 2004]. Recently translated records obtained from a computer hard disk reveal that a Saudi named Ali al Omari was a student at this camp in February of 2000..</div>
    <div class="CIA_34 box">A source in Moscow who happens to work under the direction of Pyotr Safrygin at Central Russia Airlines says he drove Safrygin to a location near Strizhi on 1 September where Safrygin met a man in a farm house. The source says Safrygin gave the man a bag, probably containing rubles, and received a package about the size of four shoeboxes that was marked [in Russian] "antibiotics". On the way back to Moscow, the source said Safrygin told him that these antibiotics were to be sold on the black market in Africa..</div>
    <div class="CIA_35 box">From information obtained from the Center of Disease Control [CDC} it was learned that 97 cases of foot and mouth disease have been confirmed in the vicinity of Bucaramanga in Columbia. CDC says these cases all appear to be FMD type A..</div>
    <div class="CIA_36 box">Grigory Sizov, a former Soviet chemist who now teaches at a university in the USA, was asked what he could tell us about Boris Bugarov and his work in Cuba. Sizov said he knew Bugarov personally and had met him on a visit Sizov took to Moscow in 2002. Sizov said that Bugarov regards Castro as a buffoon but stays in Havana because he enjoys the climate and can make much more money there than in the former Soviet Union. Sizov also said that Bugarov showed him a picture of an attractive Cuban woman whom Bugarov said he planned to marry. Sizov said that Bugarov told him almost nothing about his work in Cuba. However, he said he was free to travel and had some very capable assistants who helped him with all sorts of things. Sizov said he guessed that Bugarov might still be involved in BW work but might also be involved in the distribution of narcotics. Finally, Sizov said he could not help noticing the several flashy diamond rings Bugarov was wearing when they met..</div>
    <div class="CIA_37 box">In the CIA Report for 13 February, 2004 it was noted that Pakistani intelligence had agreed to keep a residence at 631 Nishtar Rd. in Karachi under surveillance. On 17 September, 2004 they reported to us that events had prompted a raid on this residence on 5 September, 2004. During this raid five persons were killed, among them two police officers. The three others killed were identified as: Abdul Jabarah [a Kuwaiti], Fahd Jehani [a Saudi], and Ramzi al Shibh [a Yemeni], all of whom are known members of Al Qaeda. Jehani seems to have been a courier since he was carrying a packet of messages. Most of the messages contained instructions for insurgent activities in Pakistan, including an attempt to be made on 1 October, 2004 to destroy police HQ in Karachi. But one message was addressed to S. H in Chitral that read; "Allah, all praise to him, has provided the funds you need to finish your work. These funds will be on their way in ten days." This message was sent by a person only identified as Moataz [possibly an alias] and was sent from Gwadar, Pakistan..</div>
    <div class="CIA_38 box">MI 6 provided additional information on the Malaysian named Ali Sufaat. It is now known that Sufaat lives at #13 Step St. in Nassau, The Bahamas. It is also known that Sufaat now works as a deck hand on the Island Freight Lines that makes regular runs between Nassau and Santo Domingo. Sufaat has been under surveillance and has had several contacts with Omar Hanif at the Seashore Hotel in Nassau..</div>
    <div class="CIA_39 box">Our source has now been employed by the Holland Orange Shipping Lines in Casablanca. He has been assigned to keep track of the activities of Abdellah Atmani. This source says that on 5 October, 2004 Atmani had a visitor wearing the uniform of a First Officer of Central Russia Airlines. This person gave Atmani a carefully wrapped package marked [in Russian] "Antibiotics". The source says that Atmani told the officer that he should tell his boss that this package will be aboard the "Dutch Courage" in good time. Later the same day, this source says he observed Atmani placing a Holland Orange shipping label on this package to an address in Santo Domingo, The Dominican Republic. The source could not see the street address to which this package would be sent..</div>
    <div class="CIA_40 box">A case officer who is at the American embassy in Riyadh says he overheard a conversation at an embassy party between the Spanish ambassador to Saudi Arabia and an American consular official regarding the employment of Saudis in foreign embassies. During this conversation the Spanish ambassador mentioned that an entire family, of the name al Ghamdi, had worked at the Spanish embassy in Riyadh from 1970 to 1988. The ambassador went on to say that he had worked at this embassy as a clerk during this time and had become attached to the three al Ghamdi sons. He added with regret that all three of the boys, whom he had watched grow up, left Saudi Arabia and that two of them had been killed fighting for Al Qaeda in Afghanistan. The third son, he added, never returned to Saudi Arabia and the last he heard was that he had taken up residence in Santo Domingo and was now a cab driver..</div>
    <div class="CIA_41 box">
Additional information was requested on 2 November, 2004 of the source who reported on the activities of Pyotr Safrygin on 1 September, 2004 [see CIA Report for 15 September, 2004]. This source was asked if he recognized the person at the farm house from whom Safrygin had received the package marked "antibiotics". This source said he did not recognize the person at the farm house, but said he later learned that the farm house was owned by a scientist at Vector..</div>
    <div class="CIA_42 box">This source, assigned to cover the activities of Omar Hanif, reported that on 1 December, 2004 he had followed Hanif as he took an inter-island ship called the "Packet" from Nassau to Freeport in the Bahamas. Hanif was carrying a package that the source said carried a label in what he thought was Russian [but which he could not translate]. The source followed Hanif to the Freeport Star Hotel where, in the hotel's parking lot, he gave the package to a person named Muslih Odeh, who is also under surveillance. The source said that Odeh placed the package in the trunk of a car and immediately drove off..</div>
    <div class="CIA_43 box">Received information from a source following Omar Hanif that yesterday [15 December, 2004], Hanif met two men as they departed from the cruise ship "Viking Holiday". The source said that Hanif had taken these men to his residence at 11 Apple St. in Nassau..</div>
    <div class="DIA_01 box">Interrogation of Abdul Ahmed Nasser, a Saudi born October 1967 in Abba. Captured 3 February, 04 at Baglan. Entered fight against Russians in Chechnya in 1997; went to Afghanistan 1999; provided chemical weapons training to Taliban/Al Qaeda members. Very talkative and says he has former students now in the USA who will shortly have lots of cocktails for "American alcoholic bastards."..</div>
    <div class="DIA_02 box">Interrogation of a man calling himself Kamal Abdullah who says he a Jordanian; captured near Asadabad on 1 February, 2004. Came to Afghanistan in 2000 for training with Al Qaeda, Says he has gone back and forth from Afghanistan to Pakistan on several occasions. Asked where he went in Pakistan, Abdullah said he had usually gone to Chitral, where he stayed at a refugee camp. He said he was last there in December, 2003. Asked if he knew any prominent Al Qaeda persons seeking refuge in Chitral, Abdullah could only name three: Ali Sittah, an Egyptian who had been on the central staff of Al Qaeda; Talat Rushdi, also an Egyptian who ran the Omar training camp in the Khost area, and Saeed Hasham, a Saudi who had been in charge of planning insurgent missions against the Americans..</div>
    <div class="DIA_03 box">A Saudi named Khaled Jehani was captured near Feyzabad on 16 February, 2004. When captured Jehani was carrying a laptop computer which, when examined, was found to contain an assortment of information regarding the SCADA system in the USA that controls, among other things, our electric grid and natural gas pipelines. This information had been obtained from an Internet site in the USA. In addition, this laptop computer contained a variety of information regarding the construction of e-bombs [electromagnetic pulse bombs]. On further interrogation of Jehani, he was found to have been trained in computer science at the University of Maryland where he obtained his BA degree [1995] and MA degree [1997]. A list of contacts was found along with information about the SCADA system, two of whom are in the USA. The two persons in the USA are: Abu Somad and and Yazid Bafaba in Los Angeles, CA. One name in the USA and one in Canada were found along with the information about e-bombs. The Canadian person is R. Derwish [Windsor] and the American is Abdul al Nami [Detroit]..</div>
    
    <div class="FBI_01 box">This report concerns a bulletin issued on 2 April, 2003 by the Surete' de l'Etat in Paris concerning a Moroccan named Abdillah Zinedine, alias: Abu Hafs [See CIA report for 17 April, 2003].The Surete' reported that Zinedine left Paris on a flight to Montreal, Canada on 1 April, 2003 and was traveling under a French passport in the name of Mehdi Rafiki. A Mehdi Rafiki did arrive in Montreal on 2 April, 2003 and said the purpose of his visit was to attend the funeral of an uncle. He listed his Montreal contact address as 175 Rue Durocher. This address belongs to an Irish pub operated by a man named Patrick O'alley. O'alley says he never heard of any person named Mehdi Rafiki. But a man using a French passport in the name Abu Hafs rented a car at the Canadauto Car Rental Agency in Montreal on 2 April, 2003. This rented car was never returned to this agency. It was discovered abandoned on Walden Ave near Schiller Park in Buffalo, NY on 6 April, 2003..</div>
    <div class="FBI_02 box">Riyad Yasser, a UK citizen, was arrested on 1 May, 2003 following an accident on the M4 Motorway near the Heston Service Area outside of London. Yasser has been an air traffic controller at Heathrow Airport for the past six years. Two kilos of Semtex were found in the trunk of his car. A videocassette of a sermon given by Omar Mahmoud Othman, formerly a Salafi jihad preacher at the Baker St. Mosque in London, was found in Yasser's apartment at # 44, Northumberland Circle, East Bedfont, London. Also found in Yasser's apartment was a note containing several addresses in Canada, the USA, and in Nassau in the Bahamas. The addresses are: 721 St. Clare St., Montreal; 455 11th Street, Miami Beach, FL; 1712 Ferry Ave., Camden, NJ, and 11 Apple St. in Nassau, The Bahamas..
</div>
    <div class="FBI_03 box">In response to the CIA report [29 June, 2003] regarding Abu Somad, 235 Buckthorn St, Inglewood CA, and Yazid Bafaba, 773 Flaxton St., Culver City, CA., investigators visited these two persons at their residences. Both Somad and Bafaba said they had never heard of persons named Riduan Sungkar or Omar Evertts. Each of Somad and Bafaba was asked if they knew the other and they replied that they did not. However, it was later established that both Somad and Bafaba appeared together in a surveillance photo taken at the CalNational Bank in Culver City. Records of this bank indicated that Somad and Bafaba hold a joint account at this bank and that they have received several deposits of $1000 to this account from BMI, a private Islamic investment company in Newark, NJ..</div>
    <div class="FBI_04 box">A man using an Illinois driver's license in the name Abu Hafs, address 2211 Cermak Rd.. in Chicago, rented a car at the Drexel Car Rental Agency in Chicago on 27 September, 2003. This car was never returned to the Drexel agency. It was found abandoned in a parking lot at O'Hare Airport on 2 October, 2003. On 27 April a roundtrip airline ticket to Hobby Airport in Houston, Texas was issued by Central States Airline at O'Hare Airport to a man who gave his name as Mehdi Rafiki. Rafiki paid for this ticket in cash and used as identification a French passport in the name Mehdi Rafiki..</div>
    <div class="FBI_05 box">In identifying the presence of possible Hezbollah members in the Charlotte NC area, the name Rifai Qasim, has recently surfaced. An Egyptian passport in the name of Rifai Qasim was found recently on the floor of the Southern Trailways bus depot in Charlotte, NC. Examined by the Charlotte police, the picture on this passport matches the appearance of a person using the name Omar Blakely, who was charged with the theft, on 1 October, 2003, of several items [total value: $3000] from an electronics supply store in Charlotte. Blakely gave his address as: 3131 Western Ave. in Charlotte. Blakely is now out on bail that was guaranteed by a bail bond company named BailOut, in Charlotte, NC. The $2,000 that this bond cost was paid by a check written on an account at the Carolina First Bank held jointly in the names: Omar Blakely and Muhammed Mustafa. Bank records reveal periodic deposits to this account, usually in the amount of $3000, from an account at the First Emirate Bank in Dubai, UAE. The Carolina First Bank account in the name of Blakely and Mustafa was closed on 23 October, 2003 and the house at 3131 Western Ave is now unoccupied. However, a search through this abandoned house revealed the envelopes of several letters addressed to Rifai Qasim..</div>
    <div class="FBI_06 box">Regarding Jamal al Quso, who was said by MI 5 to have come from London to Chicago in 1999 [see CIA report for 16 May, 2003], the Chicago FBI field office responded by reporting that a Jamal al Quso had landed at O'Hare Airport on July 18, 1999 using a British passport in his name. A check with USCIS reveals no evidence that he ever left the USA since his arrival. In addition, the name Jamal al Quso has been associated by an informant with Islamic Jihad, which is known to have a presence in Chicago. On 28 September, 2003 a house at 2211 Cermak Rd. in Chicago, said by the informer to be occupied by members of Islamic Jihad, was raided by an FBI team acting under a warrant. One person, Abdul Murad, was the only person at this residence at the time of the raid. Thirty kilos, of C-4 plastic explosives were found at this residence along with an additional 25 kilos of Semtex. Maps of O'Hare Airport and diagrams of the Sears Tower were also confiscated. Murad, now being held, has refused to say who the other occupants of this residence are. However, on a notepad found in the room Quso possibly occupied at this residence was listed the message [in Arabic]: "Jamal, call Khalid S., Texas, tomorrow for sure." Jamal al Quso's present location is not known..</div>
    <div class="FBI_07 box">RCMP reported the apprehension at Toronto Airport on 1 November, 2003 of a man posing as a Dominican priest. This man was traveling from CDG, Paris on a French passport under the name: Fr. Augustin Dominique, having the address 174 Rue Cardinet, Paris. When asked a question about his destination in Toronto, the man mistakenly answered in Arabic rather than in French. CSIS have identified this man as Abdal al Hawsawi, a Saudi now known to have been associated with a chemical weapons expert in Afghanistan named Abdul Ahmed Nasser. On the ticket folder Hawsawi was carrying appeared the address: 1712 Ferry St, Buffalo, NY..</div>
    <div class="FBI_08 box">On 1 November, 2003 Mousa Salah, of no fixed address in Herndon, VA., was arrested at Dulles International Airport as he attempted to board a flight to London Heathrow. At the time of his arrest he was using a Jordanian passport in the name Shadi abu Hoshar. Salah has been wanted in connection with Hamas fund-raising and other activities in Northern Virginia. It is believed that Salah entered the USA illegally from Windsor, Canada into Detroit, MI in 2002. Salah was in possession of a Virginia driver's license # T21-23-8820 registered in the name Mousa Salah. Virginia DOT records show that this same license number was issued on 10 August, 2001 to a woman named April Stevens of Roanoke, VA. Ms Stevens is not the subject of further investigations; she teaches kindergarten classes in Roanoke. The address shown on Salah's driver's license does not exist. Several numbers and initials were written on the back of an envelope in possession of Salah at the time of his arrest; they are: (i) J. T., Detroit, (ii) A. H., Newark, (iii) M. M., Laurel..
</div>
    <div class="FBI_09 box">Among the persons under surveillance for possible Al Qaeda associations in the USA is Khalid Shamrani, a Saudi national who lives and works in Houston, Texas for the TexEast Petroleum Co. Shamrani has held a work visa since April, 2000. Suspicion first fell on Shamrani as a result of his attendance at a meeting of God's Aryan Militia in Denton, Texas on 12 March, 2003. He attended another meeting of this militia group in Mineral Wells, Texas on 16 June, 2003. An FBI informant who attends the meetings of this militia group developed a friendship with Shamrani and was invited to his home at 3236 Pine St. in Bellaire, Texas. The informant says he there saw elaborate diagrams of the Houston Ship Channel and detailed plans for Reliant Stadium and the Galleria Shopping Mall in Houston. The informant also said that Shamrani revealed his association with an Islamic group that had many of the same objectives as God's Aryan Militia including the elimination of Zioni st influence on the US government. The informant also reported that Shamrani said there would be "big events" in Houston, Chicago and in other places during the next year, but he did not elaborate on the nature of these events..</div>
    <div class="FBI_10 box">Ahmed Doha and Abu Ayyash are both registered as graduate students at the University of Missouri in Columbia, MO. Both Doha and Ayyash have Saudi student visas issued in July, 2001. Doha was charged with filing a fraudulent insurance claim. On 10 October, 2003 Doha filed a claim with Ayyash's insurance company, Central Farmers Auto Insurance Co., for a back injury he said he suffered on 12 September, 2003 when his car was struck from behind by one driven by Ayyash. Doha's insurance company is the Mid States Insurance Company. Both the Mid States and Central Farmers representatives who subsequently investigated the accident and who handled this claim both stated that Doha and Ayyash said they did not know each other. Doha was paid $11,000 in settlement of this claim on 1 November, 2003 by Central Farmer's Insurance Company. A check of the records at Mid States and Central Farmers insurance companies reveals that both Doha and Ayyash paid for their auto insurance policies from the same account at the Columbia First State Bank. On a valid search warrant, Doha's apartment at 231 12th St. in Columbia was searched on 20 November, 2003 and it was discovered that Ayyash also lives in this apartment. A Dell laptop computer at this residence was taken by the police. Also taken were CDs containing a 7,000 page version of the Encyclopedia of Jihad. The computer, when examined, revealed e-mail messages to and from over 100 addresses in the USA. Many of these messages seemed to involve only personal and academic matters. But one message that attracted attention was sent on 3 November, 2003 to an AOL address for a person identified as wshakur. This message read: "4,000 you requested sent by wire today." This e-mail address belongs to Wali Shakur, who lives at 224 Paulson Ave. in Clifton, NJ. Both Hamas and Al Qaeda are known to have a presence in Columbia, MO. An investigation continues regarding the possible association of Doha and Ayyash with these groups..</div>
    <div class="FBI_11 box">In response to a request, the FBI searched its files for information on subjects having the initials J. T. [in Detroit, MI], A. H. [in Newark, NJ], and M. M. [in Laurel, MD]. Eight persons with initials J.T. were discovered in Detroit, but all these persons are known to the police and have no interesting information in their files. One person was identified with the initials A. H. in Newark; his name is Adnan Hijazi. Hijazi had been interviewed by the FBI following the 9/11/01 attacks. He was cleared of any association with these events and presently has no other entries on his record. There are just two persons in FBI files for Laurel, MD with initials M. M. One is Martha Mason and her file reveals that she was convicted on 21 January, 2002 for the distribution of narcotics; she is now incarcerated. The other is Mounir Mzoudi, of Moroccan descent, who holds a degree from Baltimore City College, which he obtained in 1994. Mzoudi currently lives at 2116 27th St. in Laurel, MD. Mzoudi recently attracted the attention of the FBI because, according to a source in Baltimore, Mzoudi had a past association with an organization called the Islamic Circle of North America [ICNA]. He attended a meeting of ICNA held in Baltimore from June 20 to July 2, 2000. ICNA quite openly supported the Taliban at this time..
</div>
    <div class="FBI_12 box">A tip from an anonymous source directed investigators to a residence at 2111 Troost Ave. in Kansas City, Missouri. This source said that explosives were being manufactured at this residence by some terrorists who intended to blow up several buildings in the Kansas City Area. A warrant was obtained to search this residence on evidence provided by an examination of items found in garbage sacks that were picked up by an FBI officer posing as a garbage collector. Traces of chemicals necessary to produce explosives were found on items in this garbage. When this residence was searched on 22 December, 2003, one man, who gave his name as Walter Smith, was the only person at home. While the investigation was proceeding, another man entered and was apprehended. Subsequent identity checks revealed this man to be Jamal al Quso, who had come from Chicago to Kansas City. What was found at this residence were batches of hexamethylene triperoxide diamine [HMTD] and cyclotrimethylene trinitramine [RDX], both primary explosives. Also found were three garbage sacks full of urea and aluminum sulfate. In later investigations of this residence, detailed drawings were found of three popular casinos in the Kansas City area: the Argosy Riverside Casino, the Isle of Capri Casino, and Harrah's Casino..</div>
    <div class="FBI_13 box">On 26 December, 2003 two men were arrested during a robbery attempt at the FirstTex Bank at 435 Fielder Rd. in Arlington, Texas. The two men, both wearing ski masks, were apprehended by Arlington police as they fled from the bank. The men were identified as Saeed al Nami and Riyad al Taifi, both living at 2727 Robinson Rd, Apartment 6, in Grand Prairie, Texas. Each one had a Texas driver's license that was forged, and neither could produce a passport of any kind. They both said they had entered the USA from Mexico at Presidio, Texas and had come to Mexico by way of Central America from Columbia. Both spoke perfect English and were unemployed at the time. An investigation of their residence revealed money in bags identified as belonging to several other banks in the Dallas area. The total amount in the bags amounted to $42,010. In addition, there were small arms of various sorts and literature concerning jihad activities. They rented this apartment from a woman named Ruth Tucker, who said that they had lived in this apartment for three months, had never caused any trouble, and paid their rent on time. She also said that they had told her they were students at the University of Texas in Arlington. One item of mail was discovered in their apartment; it was a letter written in Arabic from a person named A. Doman who gave a return address on the envelope as 231 12th St. in Columbia, MO..</div>
    <div class="FBI_14 box">Based on the information about Wali Shakur, noted in the FBI report of 27 November, 2003, agents were sent to interview him at the 224 Paulson Ave. Clifton NJ address given in this report. Before this interview information was obtained about Shakur's background. He is an American citizen, having been born in 1970 in New Brunswick, NJ of parents who were immigrants from Pakistan in 1965. Shakur attended Rutgers University for two years , dropping out in 1990 in order to study at the American University in Beirut, Lebanon. He returned to the USA in 1993. Shakur was shown a copy of the e-mail he had received from either Ahmed Doha or Abu Ayyash on 3 November, 2003. He was also asked what the 4,000 in this message referred to. Shakur replied that both Doha and Ayyash were students at the University of Missouri and were good friends of his father and that he, Shakur, did not know them personally. Shakur said that his father had in 2001 loaned them $8,000 and had not yet received any payment on this loan. Shakur said he requested at least half payment on this loan and later received a Western Union wire of $4,000 from Doha. Shakur said he gave the cash to his father. Asked for his father's address, Shakur said his father had died on 2 January, 2004. Shakur's activities remain the subject of FBI investigations..</div>
    <div class="FBI_15 box">Jamal al Shibh, of Yemeni origin, has been the Imam at the Tawhid Mosque in Miami, Florida for the past ten years. As a result of recent reports provided by informants about al Shibh's call for jihad in America, he has been under surveillance. He was photographed on 2 February, 2004, on the University of Miami campus in Coral Gables, distributing literature, written in Arabic, at various locations known to be frequented by Islamic students. This literature describes how well the city of Miami illustrates that America has become a sink of vice and corruption. Examples are provided of the easy availability of sex and drugs in the Miami area. This literature also calls for immediate jihadic action in order to prevent the corruption of Muslims in America. Especially singled out in this literature is the tourist industry in the Miami area..</div>
    <div class="FBI_16 box">Update on the surveillance of Adnan Hijazi. Checks with airlines reveal that he made three trips overseas in the last three months: Madrid, Spain [1 - 5 December, 2003]; Cairo, Egypt [21 - 24 December, 2003]; Paris, France [ 12 - 18 January, 2004]..</div>
    <div class="FBI_17 box">Further information regarding the activities of Jamal al Shibh. When he was observed distributing the jihadic literature on the University of Miami campus, he was accompanied by a person who has now been identified. He is Muhammed Dandani, whose residence is 455 11th St. in Miami Beach, FL. There is no further information about Dandani..</div>
    <div class="FBI_18 box">In response to a DIA report of 5 March regarding Abdul al Nami, a check was made of persons with this name in the Detroit area. There are two persons having this name in the Detroit area. One lives at 562 Fenkell Ave. and the other lives at 766 Livernois Rd. Neither of these two persons have been the subject of FBI investigations in the past. It is now known that the 562 Fenkell Ave. resident is employed as a computer scientist by Detroit Utilities Co. and has worked there for seven years. He holds an American passport giving this address and has lived in the USA for ten years. The resident at 766 Livernois Rd. is a history teacher at the Westfields High School in the Ferndale area and was born in the USA of Saudi parents in 1969. Investigation of these two persons continues..</div>
    <div class="FBI_19 box">Further information regarding Saeed al Nami and and Riyad al Taifi who were apprehended on 26 December, 2003 during a robbery attempt in Arlington, Texas [see FBI report 2 January, 2004]. Both of these individuals are Saudis who came to Buenos Aires, Argentina in January of 2001. They are both wanted by the police in Buenos Aires for their role in the bombing of a Jewish synagogue in Buenos Aires in April of 2002. Escaping apprehension, they went to Calamar, Columbia in May, 2002, where they are now known to have been active in collaborating with the ELN. In January, 2003 they came to the USA following a route taken by other Islamic militants known to have come into the USA. This route took them from Calamar to Cartagena in Columbia and then by boat to Guane in Cuba. They then went by boat from Guane, Cuba to Chetumal, Mexico. From Chetumal they traveled to Mexico City and then on to the border town of Ojinaga, where they were smuggled into Presidio, Texas. In Ojinaga they were both supplied with Texas driver's licenses and U.S. currency by a person whose name they said they could not remember. They went by bus to Ft. Stockton, San Antonio, and then on to the Dallas area. A search of their apartment at 2727 Robinson Rd. in Grand Prairie, Texas revealed an assortment of automatic weapons and the addresses of two men known to be associated with God's Aryan Militia in Texas. These men are Billy Jack Hawkins, 1212 Pipeline Rd., Euless, Texas, and Slade Goodman of 899 Almeda-Genoa Rd. in Houston, Texas..</div>
    <div class="FBI_20 box">Further information about Abdul al Nami who works as a computer scientist for the Detroit Utilities Co. [see FBI report 8, March, 2004]. Nami came to the USA from Saudi Arabia in 1994 on a student visa to attend the University of Michigan at Ann Arbor. He earned an MA 1996 in computer science and was granted a green card in 1997 for work at the Detroit Utilities Co. He applied for U.S. citizenship in 1999, which was granted in April of 2000. Officials at the Detroit Utilities Co say that al Nami is a splendid worker who has intimate knowledge of the SCADA system and was instrumental in increasing the efficiency of electric power distribution in the Detroit area. Officials said he took a six-months' leave of absence in January, 2001 to visit his family in Riyadh..</div>
    <div class="FBI_21 box">Received information from MI 6 about Imad Dahdah, who resides at #65 West End Ave. in Nassau, The Bahamas. Dahdah was born in Syria in 1964 and came to the UK in 1994. He became active in Islamic affairs and regularly attended the Baker St. mosque. He obtained British citizenship in 1998 and travels under a British passport. He traveled to Afghanistan in 1999 - 2000 and is now suspected of having been trained at an Al Qaeda facility during this time. Dahdah returned to the UK in March of 2000 but left for The Bahamas in June of 2000. He works at an auto repair shop for a minimum wage but is now known to receive periodic funds from an account at the Gulf Shores Bank in Tampa, FL. The account from which these funds are drawn belongs to an organization named Middle Eastern Charities..</div>
    <div class="FBI_22 box">Information received from MI 5 regarding Raeed Beandali, an American citizen who was listed on Al Qaeda rosters [see CIA report 15 Feb. 2003]. According to this roster, Beandali was sent from Afghanistan to London on 12 December, 2002. MI 5 tells us that a man was arrested in London on 10 February, 2004 for carrying an unregistered British driver's license. The name on this license was Reginald Cooper and the address given on this license was # 12 Lavender Grove, Hackney, London. When he was arrested, Cooper told police constables that he lived alone with his old Mum at this address. Inquiries made at 12 Lavender Grove revealed that it was occupied by several men, one of whom was identified by neighbors as a "nice American" who called himself Ralph Bean. An assortment of materials for constructing explosive devices were found in a shed behind this residence. Reginald Cooper was subsequently identified as Mahmud al-Dahab, an Egyptian who had been living in London for about 15 years. Asked where Ralph Bean was to be found, all Cooper [al Dahab] would say is; "He went home". Checks with airlines revealed that a Ralph Bean, traveling on an American passport, left London Heathrow on 16 March, 2004 for Detroit MI..</div>
    <div class="FBI_23 box">The bail bond company BailOut in Charlotte NC forfeited the $10,000 bail bond it guaranteed for Rifai Qasim [alias Omar Blakely] in connection with the theft charge against him [see FBI Report 25 October, 2003]. When this bail bond company's investigators failed to locate Qasim/Blakely after four weeks, they turned the matter over to the FBI. Qasim and his associate Muhammed Mustafa closed their joint bank account at the Carolina First Bank on 23 October, 2003 and fled in a 1997 Toyota Tercel, NC license # TQE-732. A 1997 Toyota Tercel bearing this license number was found abandoned in River Rouge Park in Detroit, MI on 15 December, 2003. Overlooked in the initial examination of this vehicle by Detroit police, but later found by FBI investigators, was a slip of paper with a phone number on it. The phone number is listed in the name Abdul al Nami, who resides at 562 Fenkell Ave. in Detroit, MI. Acting on information obtained in DIA Report 5 March, 2004, a court-sanctioned tap was placed on this phone. On 15 May, 2004 a call was placed from this phone to a residence at 237 Hayes Ave in Detroit. The caller said: "Rifai, we are all together now. We will let you know when the match will be played. It might take some time to get the right field." The person receiving the call says: "I hope it will not be too long, my side is really ready to play." Investigators went to the residence at 237 Hayes Ave. on 20 May, 2004 and found it to be unoccupied. Neighbors said that the two Middle Eastern men who had occupied this residence briefly had moved out just a few days earlier. The owner of this residence, a Mr. Howard Clark, said he had evicted the two men because they failed to pay their rent for two months. Clark did not know where they went..</div>
    <div class="FBI_24 box">More information is available about the overseas trips taken by Adnan Hijazi. In Madrid, between 2 - 5 December, 2003, he stayed at the Catalan Hotel and attended a three-day textiles convention. In Cairo, between 22 - 24 December, 2003, he stayed at the Luxor Hotel. During his stay in Cairo at this time he made regular visits to a jewelry shop at 411 Ramses St. in Cairo. In Paris, France, between 13 - 18 January, 2004 he stayed at the Hotel de St. Marie and attended daily meetings at the Paris offices of Overseas Exports Inc..</div>
    <div class="FBI_25 box">The FBI informant who attends meetings of God's Aryan Militia [GAM] in Texas reports having recorded a conversation between Khalid Shamrani [see FBI Report: 20 November, 2003] and three other men, two of whom the informant identified as Billy Jack Hawkins and Slade Goodman, both of whom are members of GAM. The third person our informant could only identify as a Middle Easterner named "Hafs" or "Halfs". This was the name given him by Shamrani. The gist of this conversation, which took place at the Westerner Motel on Almeda-Genoa Rd. in Houston, was that actions involving destructive activities in the Houston area and elsewhere would be placed on hold for at least several months. They discussed the apprehension of a militia member named Walter Smith and another person named al Quso in Kansas City. The fear they expressed was that their actions were being compromised..</div>
    <div class="FBI_26 box">This report concerns results of an FBI interview of the two men apprehended in Carrizo Springs, TX on 3 August, 2004 [See USCBP Report for 11 August, 2004]. Both men spoke perfect English and were very cordial. But they refused to answer any questions and asked to be represented by an attorney. They were fingerprinted and held in custody. Further examination of documents in their possession when they were apprehended revealed a letter, written in Arabic, from a person named Abdul Nasser. This letter was addressed to a person named Ali al-Omari. This letter simply said: "Go forth with Allah's blessing. You have been my best student." Investigation of these two men continues..</div>
    <div class="FBI_27 box">This report concerns continuing surveillance of the activities of Adnan Hijazi. During the period 20 August to 18 September, 2004 Hijazi made thirteen cash deposits to his personal account at the Jersey National Bank in Newark, NJ. These deposits totaled $47,980..</div>
    <div class="FBI_28 box">Information was requested of Belgian intelligence by the FBI on 1 September about Pieter Dopple, who lives at 22 Hoveniersstraat, Antwerp, Belgium. He sent the diamonds to Adnan Hijazi as noted in the USCBP report of 12 July, 2004. Belgian intelligence reports that Dopple has been under surveillance as a fence for diamonds obtained by groups, many of them associated with Islamic ventures, in various places in Africa. It appears that Dopple receives raw diamonds and other precious stones such as tanzanite and cuts and polishes them for distribution. Dopple receives a fee for his services but does not sell the stones himself. He sends them where his suppliers specify. At his interrogation, Dopple admitted that he was part of a scheme for transferring funds for militant Islamic groups and agreed to cooperate with investigators. He listed several persons in addition to Hijazi to whom he had sent polished diamonds and tanzanite. One person he named was Ramundo Ortiz, who runs a business in Panama City, Panama. He further said that he had just sent about $150,000 in polished diamonds to Ortiz on 25 September. Asked for the identity of the person(s) who had requested this transaction, he could only say that they were from Peshawar in Pakistan..</div>
    <div class="FBI_29 box">This special alert concerns assorted vulnerabilities of the SCADA systems. These Supervisory Control and Data Acquisition systems manage the actual flow of electricity and natural gas and perform other critical functions in a variety of other industries including chemical processing plants, water purification systems, delivery systems, and other manufacturing systems. SCADA is largely controlled and maintained by U.S. industries and crucial operations of SCADA are widely available on the Internet. Unauthorized access to SCADA is a constant source of concern. SCADA could be accessed from home computers and laptops. Of special interest are vulnerabilities associated with "trusted insiders."..</div>
    <div class="FBI_30 box">Continuing surveillance of Adnan Hijazi reveals that, on 14 September, 2004, he sent a bank wire transfer of $48,000 to the account of an organization called the American Islamic Scholarship Fund, which is located at 1721 Glade Dr. in Reston, VA..</div>
    <div class="FBI_31 box">Acting immediately in response to the FBI HQ alert of 11 October, 2004, the Detroit office began an enhanced surveillance of four individuals known to be in the Detroit/ Windsor area who might be involved in activities designed to disrupt SCADA systems. These persons are: Satam [alias Ronald] Derwish, 811 Tecumseh Rd., Windsor, Ontario; Abdul al Nami, 562 Fenkell Ave., Detroit; Rifai Qasim, address unknown; and Raeed Beandali [alias Ralph bean], address unknown. The cooperation of the RCMP was requested in following the activities of Derwish. Investigators went immediately to al Nami's residence at 562 Fenkell Ave. but found he was not at home. Checks with his employer, Detroit Utilities Co., revealed that he was on a week's vacation in Canada and would be back to work on 20 October, 2004. His employers at Detroit Utilities were strongly advised not to reveal to al Nami that he was under investigation..</div>
    <div class="FBI_32 box">Our informant in God's Aryan Militia advises that he has not seen Khalid Shamrani for nearly a month and that efforts to contact him at his home in Bellaire, Texas have been unsuccessful. Investigators immediately went to TexEast Petroleum Co. where Shamrani has been employed. Officials at this company said that on 18 September, 2004 Shamrani had requested a month's leave of absence in order to return to Saudi Arabia to be with his dying mother. Shamrani had been placed on a watch list and subsequent checks with USCIS reveal that no one named Shamrani had left the USA in the past month..</div>
    <div class="FBI_33 box">Investigation of the residence at 3236 Pine St. in Bellaire, Texas revealed a receipt for the rental of a storage unit # 124 at the StoreAll Rental facility at 4618 Bissonnet St. in Houston. Unit 124 was empty but careful examination of it revealed traces of C-4 and Semtex. The owner of StoreAll Rental said that the renter of unit 124 had told him on 15 October, 2004 that he would not need this unit any longer. The owner remembered that four men, using a RentAll truck had removed the contents of this storage unit the next day..</div>
    <div class="FBI_34 box">The RCMP reported to us the results of their investigation of the activities of Satam [alias Ronald] Derwish, 811 Tecumseh Rd., Windsor, Ontario. On 25 October, Derwish was approached by officers at his place of work at Canada Eastern Airlines in Windsor. The officers said that Derwish agreed to accompany them to the RCMP main office in Windsor. During his interview Derwish denied having any contact with a person in Marrakech, Morocco [see NSA Report: 1 July, 2003; also see DIA Report: 5 March, 2004] and said he had no idea who "Abdul" was. Shown a photo of him [Derwish] in company with Abdul al Nami in Detroit on 18 July, 2004, Derwish said: "I never knew him by the name Abdul; I knew him as Ali. We have attended the same mosque in Detroit. "Subsequent court-approved investigation of Derwish's residence revealed an assortment of copper tubing, copper wires, batteries, and a supply of conventional explosives, all of which are components of an electromagnet ic pulse bomb. Derwish was held in custody and investigations continue..</div>
    <div class="FBI_35 box">On 29 October, 2004 investigators went to the offices of the American Islamic Scholarship Fund located at 1721 Glade Dr. in Reston VA. There they interviewed the director of this fund, a man named Abdul Karim. Karim led the initial discussion and described how many deserving students of Islamic descent had been assisted by this scholarship fund since it was begun in 1991. Karim was first asked if this Fund did indeed receive the $48,000 scholarship donation made by a man named Adnan Hijazi on 14 September, 2004. Checking his records, Karim verified the receipt of this donation by Karim. Then Karim was asked for the names of persons who received money from this donation from Hijazi. Karim hesitated at first and then said: "Every now and then we receive money from donors who identify the students to whom the scholarship money should go. This happened in the case of Hijazi's donation." Checking his records again, Karim said: "HIjazi stipulated that $8,000 should go to each one of the following students: Wali Shakur, 224 Paulson Ave. CLifton, NJ; Hamza al Midhar, 1641 Pitkin Ave. Brooklyn, NY; Mounir Mzoudi, 2116 27th St. Laurel, MD; Mamoun Zammar, 1621 Charles Ave., Potomac, MD; Said Khadr, 6132 Broward Blvd., Fort Lauderdale, FL; Muhammed Dandani, 455 11th St., Miami Beach, FL." Karim then said that these amounts of money were sent to each of these persons on 17 September, 2004. Finally, Karim was asked if Hijazi had made any other donations to this fund in the past. Karim said that his recollection was that Hijazi had contributed to the scholarship fund on two other occasions, once in 1999 and once in 2001..</div>
    <div class="FBI_36 box">Results of investigation of Abdul al Nami in Detroit. As requested, al Nami arrived at the Detroit office on the morning of 27 October, 2004. He was first asked about his association with Satam [alias Ronald] Derwish in Windsor, Ontario. al Nami said that they were friends and that they attended the same mosque in Detroit. He was then asked if he had corresponded with anyone in Marrakech, Morocco; he replied that he had never done so. Then he was asked if he had ever met or had any dealings with a person named Khaled Jehani [see DIA Report: 5 March, 2004]. al Nami replied that he had never heard of this person. Asked what the nature of his work was at Detroit Utilities Co. and how it involved the SCADA systems, al Nami replied that it was his job to make sure that his company made full use of the operational characteristics of these control and data acquisition systems. Asked if he ever accessed these systems from his home, al Nami replied that the demands of his job required that he do lots of work at home at nights and on weekends. Asked if he had ever heard about a project called "Black Ice", he said he had not. On evidence supplied by the various communications received regarding al Nami, a warrant to search his residence was approved by the court. Among the items found at his residence was a document describing the results of the "Black Ice" project that was designed to assess the various vulnerabilities associated with the SCADA systems. In addition, items associated with the construction of e-bombs were also found. al Nami is now in custody as further investigation proceeds..</div>
    <div class="FBI_37 box">On 1 December, 2004 this office received in the mail a letter signed "Ramon". This letter was mailed from a post office at Gulfgate in Houston but carried no return address. The letter said that a stain of Type A foot and mouth disease was now in Texas and that cattlemen around Victoria, TX would be the first to suffer. The note also said that members of FARC had traveled from Cartagena, Columbia to Guane, Cuba, to Chetumal, Mexico, to Piedras Negras, Mexico, and then to Victoria, TX..</div>
    <div class="FBI_38 box">On 3 December, 2004 this office received a letter from a person who signed his name "Juan". This letter, having no return address, was mailed from a post office in Farmers Branch, TX. Like the letter sent to the Houston field office, this one said that a Type A strain of foot and mouth disease was brought into the USA by persons who had traveled from Cartagena, Columbia, to Guane, Cuba, to Ciudad Madero, Mexico, to Ciudad Acuna, Mexico, and then on to Victoria, TX. The letter closed by saying that this strain of FMD was a "little greeting" from FARC and the ELN..</div>
    <div class="FBI_39 box">Agents tracking domestic websites noted an item posted on a website called "Government Secrets". This website posts information that its sources claim are items of information being kept from the public by the US government. The sources are never identified on the website. On 6 December, 2004 was posted the following item:"We are always told how secure are the germ labs and storage areas are on Plum Island, just off Long Island. This is total BS. We know that fake IDs to get on Plum Island are not hard to get. And, we also know that, on 1 December, 2004, samples of a strain of foot and mouth disease was quite easily stolen from Lab 101 on Plum Island. How long is our government going to keep us in the dark about the lack of security on Plum Island. The safety of our food supply is at stake."..</div>
    <div class="FBI_40 box">An official of the Majestic Lines, a tourist ship lines reported to us an observation made on 29 November, 2004 by one of their booking agents. She said that two men with Middle Eastern names had booked two tours on the same ship for tours that left just a month apart. The first tour, aboard the "Majestic Clipper", left Miami on 15 November, 2004 for Nassau, The Bahamas, and returned from Nassau to Miami on 21 November, 2004. The second tour would leave Miami for Nassau on 13 December, 2004 and return from Nassau to Miami on 19 December, 2004. The two persons booking these tours on 20 September, 2004 were Said Khadr and Muhammed Dandani. Both held U.S. passports. They were booked for first-class accommodations on the "Majestic Clipper" for both of these tours. Khadr and Dandani took the first tour and are aboard the second..</div>
    <div class="FBI_41 box">In light of the information in FBI report for 13 December, 2004, an immediate check was made of other cruise ship lines to see if there were other occurrences of such double bookings by Middle Eastern persons. Positive replies were obtained from the Royal Norwegian Lines in New York City and the Sea Aire Lines in Baltimore, MD. Royal Norwegian Lines reported that two men named Wali Shakur and Hamza al Midhar had, on 20 September, 2004, booked first-class accommodations on the "Viking Holiday" that left NYC on 14 November, 2004 and returned to NYC from Nassau on 21 November, 2004. These same two men had booked first-class accommodations on the same ship that left NYC for Nassau on 12 December, 2004 and is due to arrive back in NYC on 19 December, 2004. This cruise ship leaves Nassau on 18 December, 2004. The Sea Aire Lines reported the following information. Two men named Mounir Mzoudi and Mamoun Zammar had, on 21 September, 2004 booked two first-class accommodations on the "Caribbean Queen". The first was for a tour that left Baltimore for Freeport, The Bahamas on 7 November, 2004 and returned to Baltimore on 14 November, 2004. The second was for a tour on the "Caribbean Queen" that left Baltimore for Freeport on 12 December, 2004 and is due to arrive back in Baltimore on 19 December, 2004. This ship leaves Freeport on 17 December, 2004..</div>
    
    <div class="NSA_01 box">Intercepted phone call, in Arabic on 28 March, 2003 from a location in London to a location in Paris. London location is: 16 Becklow Rd, Shepard's Bush; Paris location: 73 Rue Duhesme. In part of this message the caller says: "...I hope you can cook a lot of white meat in Texas..."..</div>
    <div class="NSA_02 box">Intercepted phone call in Arabic on 25 April, 2003 from a location in Amsterdam to a location in Montreal, Canada. The Amsterdam location is: 29 Grootslagstraat, Amsterdam; the Montreal location is 721 St Clare St.. In part of this message the caller says: "...the best place for father to stay in Chicago is at 2211 Cermak Rd. because the rent is very cheap..."..</div>
    <div class="NSA_03 box">Intercepted phone call from Paris to Ojinaga, Mexico. The Paris call originated from # 12 Rue De Civry; the Ojinaga location is a pay phone at the Cabrito Hotel. In part of the message, in Arabic, the caller says: "...we will let you know when S and R can make a safe passage north..."..
</div>
    <div class="NSA_04 box">Recorded e-mail traffic on AOL from the Oasis Internet Cafe in Marrakech, Morocco to the username rder3. The name rder3 belongs to a user in Windsor, Ontario, Canada. The person to whom this account is billed is R. Derwish, whose address is given as 811 Tecumseh Rd. Part of this message, in English, reads: "...all you need will be sent to you on 15 July. Do not fail to have it in Abdul's hands before 1 August, 2003..."..</div>
    <div class="NSA_05 box">Intercepted phone call on 3 September, 2003 from a location in Moscow, identified as a phone at the Central Russian Airlines offices, to a pay phone located in a bus station in Chitral, Pakistan. The caller, speaking in Russian says: "Bugarov will meet you in Casablanca on 22 October. Let me know immediately if you cannot come." The receiver of the call replies, also in Russian, but with an Arabic accent: "I will be there for sure."..</div>
    <div class="NSA_06 box">Intercepted phone call on 5 September, 2003 from a location in Nassau to one in Freeport in the Bahamas. The Nassau location is: # 11 Apple St. and the Freeport location is 1789 Grenfel Ave. The resident at the Nassau address is named Omar Hanif; the resident at the Freeport address is named Muslih Odeh. In part of this message the caller says: "Do you remember the meeting I went to in Karachi last March? I am going to offer you a promotion, will you accept it?" The reply is: "Yes, of course."..</div>
    <div class="NSA_07 box">Intercepted phone call from a location in Karachi, Pakistan to a location in Panama City, Panama. The location in Karachi is # 631 Nishtar Rd; the location in Panama City is 993 Panamico Ave. The caller says [in English]: "Can you help us sell a large assortment of very high quality tanzanite in a short time?" The person receiving the call says: "Yes, will the money go to the usual place?" The caller replies: "Yes, for this shipment, but the money from other shipments may go to other places; we will let you know."..</div>
    <div class="NSA_08 box">Intercepted phone call on 25 September from Chitral, Pakistan to Casablanca, Morocco. The call from Chitral was from a prepaid cell phone using an unlisted ID number supplied by an Internet Cafe in Peshawar. The recipient phone is listed as belonging to the loading office at the Holland Orange Shipping Lines in Casablanca. The caller begins by saying: "I have not seen you for quite a while, but I will see you at the usual place on the 20th. I'll be in Casablanca for a few days doing other business." The person receiving the calls says: "I will be glad to see you on the 20th; will you be bringing anyone else with you?" The caller says: "Possibly just one of my friends."..</div>
    <div class="NSA_09 box">Intercepted phone call from Casablanca, Morocco to Santo Domingo, Dominican Republic on 23 October, 2003. The call originated from a phone listed at the Holland Orange Shipping Lines in Casablanca; the recipient of the call was at a residence at 65 Avenue San Martin in Santo Domingo. During the conversation the caller states [in Arabic]: "You will receive a shipment of antibiotics at a time we will announce to you. At about the same time you will receive a shipment of medical supplies. We will let you know where these items will be going."..</div>
    <div class="NSA_10 box">Intercepted phone call on 15 December, 2003 from a location in Paris, France to a location in Windsor, Ontario, Canada. The Paris call was from 174 Rue Cardinet; the call was received at 811 Tecumseh Rd. in Windsor. In a brief message the caller says in French; "Mother will meet you in Buffalo on the 28th and will have what you expected." The person receiving the call says: "At Ferry St. as usual?" The caller says: "Yes."..</div>
    <div class="NSA_11 box">Intercepted phone call from Chitral, Pakistan to a location in Havana, Cuba. The call from Chitral was from a prepaid cell phone using an unlisted ID number supplied by an Internet Cafe in Peshawar. The receiver of the phone call was at the address: 16 Plasencia St., Havana, the residence of Boris Bugarov. The caller says [in Russian]: "The medical supplies will go to Morales in Santo Domingo, we will tell you when. You will receive a payment at the end of the month." The receiver says [in Russian]: "That's fine, I will let Escalante handle all the arrangements for the shipment."..</div>
    <div class="NSA_12 box">Intercepted phone call from Calamar, Columbia to Ojinaga, Mexico. The caller was using a pay phone at the Los Palmas Hotel in Calamar. The receiver was at a pay phone in the Cabrito Hotel.in Ojinaga. In a brief message the caller said: "Expect Jose and Carlos on May first. Don't let them go north until you hear from us." The receiver replies: "I know there has been trouble. But you must send us more money to cover expenses."..</div>
    <div class="NSA_13 box">Intercepted phone call from Bogota, Columbia to Tampico, Mexico. The call originated from a pay phone in the Los Andes Hotel in Bogota; the receiver of the call was at a residence at 555 La Mirada St. in Tampico. The caller began by saying [in Spanish]: "As you have heard, our Arab friends need to find a new way north. We hear that Chetumal may not be good any more. Can you recommend another stopover?" The recipient of the call replies: "Yes, we have given this some thought and recommend you try Ciudad Madero. We are close by and can provide help. This will also make the route to Ojinaga shorter. Will we have access to the same funds?" The reply was "Yes, of course. This sounds very good."..</div>
    <div class="NSA_14 box">Intercepted phone call on 5 September, 2004 from a phone at Central Russia Airlines in Moscow to an unlisted cell phone in Chitral, Pakistan. The caller says [in Russian]: "I got the first payment and have obtained what you wanted. Let me know when you wish me to deliver this stuff." The recipient of the call says: "Fine, it will not be too long now."..</div>
    <div class="NSA_15 box">Intercepted phone call on 12 September, 2004 from Tehran, Iran to Tampico, Mexico. The caller was at a phone in the Cultural Ministry in Tehran; the receiver of the call was at 555 La Mirada St. in Tampico. The caller says [in Pharsi]: "Our Crusader enemies have a saying 'Diamonds are a girl's best friend'. Do you understand what I mean?" The receiver says: "I understand completely. They will be our best friends too."..</div>
    <div class="NSA_16 box">Intercepted phone call on 28 September, 2004 from Havana, Cuba to Santo Domingo, Dominican Republic. The Havana call originated at 45 Desague St. in Havana listed in the name Jose Escalante; the destination was at 65 Ave. San Martin in Santo Domingo, listed in the name Carlos Morales. The caller says [in Spanish]: "Hello Carlos, I'm calling just to tell you that Arze will have the medical supplies to you by November 21st. You know who to give them to?" The reply is: "Yes, some guy named Sufaat. He also gets the antibiotics that I just heard about from the Arab. They will also be here by November 21st. Where is all this stuff going?" The caller says: "I don't know anything about any antibiotics. I guess we are not supposed to know, but my guess is that they will go to our friends in Columbia."..</div>
    <div class="NSA_17 box">Intercepted phone call from Bogota, Columbia to Tampico, Mexico. The call originated from a pay phone in the Los Andes Hotel in Bogota; the receiver of the call was at a residence at 555 La Mirada St. in Tampico. The caller said [in Spanish]: "Your first two guests will arrive on the tenth of this month at the new place. Make sure you tell them to avoid going north through Piedras Negras. We believe Rinaldo and Carlos have been caught." The reply is: "We will send them through Cuidad Acuna. The other place looks bad too."..</div>
    <div class="NSA_18 box">Intercepted phone call from Chitral, Pakistan to a location in Havana, Cuba. The call from Chitral was from a prepaid cell phone using an unlisted ID number supplied by an Internet Cafe in Peshawar. The receiver of the phone call was at the address: 16 Plasencia St., Havana. The caller says [in Russian]: "Have the medical supplies to Morales by November 21st for sure. As soon as I hear from him your rocks will be on the way." The reply given was: "Don't worry, my boys are very good."..</div>
    <div class="NSA_19 box">Intercepted phone call on 15 November, 2004 from Bogota, Columbia to Tampico, Mexico. The call originated from a pay phone in the Los Andes Hotel in Bogota; the receiver of the call was at a residence at 555 La Mirada St. in Tampico. The person at the residence has now been identified as a Saudi named Riyad Said. He has been using the alias "Jose Ramirez". In this call the caller says [in Spanish]: "What happened to your two guests who arrived a few weeks ago?" The reply was: "They made it just fine and the new route works great. I heard from them two days ago and they have made their destinations up north."..</div>
    <div class="NSA_20 box">Intercepted phone call on 21 NOvember, 2004 from Chitral, Pakistan to a location in Havana, Cuba. The call from Chitral was from a prepaid cell phone using an unlisted ID number supplied by an Internet Cafe in Peshawar. The receiver of the phone call was at a phone listed at the Seashore Hotel in Nassau, The Bahamas. The caller says [in Arabic]: "Any news?" The recipient says: "Six guests arrived for their first visit and were well-entertained. I received both packages and will see that the antibiotics and medical supplies get to where they are required." In reply, the caller says: "This is good news, thanks."..
</div>
    <div class="NSA_21 box">Intercepted phone call on 28 November, 2004 from Bogota, Columbia to Cuidad Acuna, Mexico. The call originated from a pay phone in the Los Andes Hotel in Bogota; the receiver of the call was at a residence at 112 Ave. Zaragoza in Ciudad Acuna. The caller says [in Spanish]: "The next time you talk to your boys up north, tell them to make sure they get their stories straight." The person receiving the call says: "Don't worry, they know what they are supposed to do."..</div>
    <div class="NSA_22 box">Intercepted phone call on 28 November, 2004 from Havana, Cuba to Moscow, Russia. The call originated from an office at a Cuban Government building at 222 Fidel St. in Havana. The call was received at an office of Central Russia Airlines in Moscow. The caller says [in Russian]: "Hello Pyotr, Boris here. I am thinking of coming home in January, will I see you?" The receiver of the call says: "I'll be gone all of January, sorry. By the way, how did you do with the Arab in Casablanca?" The caller says: "Quite well, I sold him four canisters of L-one." The receiver says: "I wasn't supposed to tell you, but I sold him two of N-one. I wonder what they will do with this stuff?" The caller says: "The Arab told me that they would use it in the Middle East, possibly against American forces in Iraq. My guess is that they will use it against the Israelis. I will tell you more about it when we meet. I just bought a new house on the beach. You ought to come for a visit; you can meet my new wife."..</div>
    
    <div class="USCBP_01 box">On 3 August, 2004 two men were apprehended at the Longhorn Motel in Carrizo Springs, TX. The motel owner, Mike Sanders, said he became suspicious of the two because of the identification they presented when they registered at his motel on 2 August, 2004. One of the men presented a Texas driver's license having a picture that seemed fuzzy. In addition, they listed a Texas car license as KHZ - 116. Sanders allowed the men to stay but made note of the address on the driver's license: 2233 Fannin St. in Uvalde, TX. Sanders informed the USCBP office in Laredo who verified that there is no such address in Uvalde, TX. In addition, there was no car in the motel's parking lot having the license plate KHZ - 116. When interviewed by USCPB officers, one of the men said their car had obviously been stolen from the motel's parking lot. Most probably, the two men had crossed the border in the vicinity of Piedras Negras and Eagle Pass. They were held for questioning. Examination of their luggage revealed several documents written in Arabic, that included instructions about how to make sarin gas and ricin..</div>
    <div class="USCBP_02 box">A routine customs inspection was performed on a package that was sent by a person named Pieter Dopple, 22 Hoveniersstraat, Antwerp, Belgium. This package was addressed to A. Hijazi, 1212 Lyons Ave., Newark, NJ. The customs form stated that this package contained two decorative clocks having a commercial value of $250.00. The package instead contained 111 polished diamonds, whose value is estimated to be $47,000. Discussions with the FBI resulted in a decision not to pursue a customs violation charge against HIjazi. The reason is that HIjazi is currently under FBI surveillance. This package was resealed and delivered to HIjazi by USPS..</div>
    
    
    
    
    
    
</div><!-----------list_container------------>

 <style>
 .active {
  color: green;
}
 </style> 	
 
 
  <script >
 
   $('input:checkbox').change(function(){
   if($(this).is(':checked')) 
       $(this).parent().addClass('active'); 
  else 
      $(this).parent().removeClass('active')
 }); 
    </script><!-----------script to select the docID------------------->


	</body>

</html>
